import { useEffect, useState } from 'react';
import { ShieldAlert, Copy, Check } from 'lucide-react';

type Transaction = {
  id: number;
  dte_type: string;
  recipient_tax_id: string;
  status: string;
};

export default function Interceptor() {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    fetch('/fel-studio/api/timeline')
      .then(res => res.json())
      .then(res => {
        setTransactions(res.data || []);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const generateFixtureCode = () => {
    if (transactions.length === 0) {
      return '// No transactions recorded yet\nFelFake::assertNothingIssued();';
    }

    const issuedCount = transactions.filter(t => t.status === 'issued').length;
    const cancelledCount = transactions.filter(t => t.status === 'cancelled').length;
    const failedCount = transactions.filter(t => t.status === 'failed').length;

    let code = `// FelFake Test Fixtures generated by FEL Studio\n`;
    code += `use InfilePhp\\Laravel\\Facades\\FelFake;\n\n`;
    
    if (issuedCount > 0) {
      code += `FelFake::assertIssued(${issuedCount});\n`;
    }
    if (cancelledCount > 0) {
      code += `FelFake::assertCancelled(${cancelledCount});\n`;
    }
    if (failedCount > 0) {
      code += `// Note: ${failedCount} transactions failed during recording\n`;
    }

    // Add specific assertions for the latest transaction if available
    const latest = transactions[0];
    if (latest) {
      code += `\n// Latest transaction assertions\n`;
      if (latest.dte_type) {
        code += `FelFake::assertType(\\InfilePhp\\Core\\Enums\\DteType::${latest.dte_type});\n`;
      }
      if (latest.recipient_tax_id) {
        code += `FelFake::assertRecipient('${latest.recipient_tax_id}');\n`;
      }
    }

    return code;
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generateFixtureCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return <div className="p-8 text-center text-slate-500">Loading interceptor...</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight text-slate-900 flex items-center gap-3">
            <ShieldAlert className="w-8 h-8 text-indigo-600" />
            Interceptor Mode
          </h2>
          <p className="text-slate-500 mt-1">Converts your real application calls into FelFake test fixtures.</p>
        </div>
      </div>

      <div className="bg-slate-900 rounded-xl shadow-sm overflow-hidden flex flex-col">
        <div className="px-4 py-3 bg-slate-800 border-b border-slate-700 flex items-center justify-between">
          <h3 className="text-sm font-medium text-slate-200 font-mono">Generated PHPUnit Fixtures</h3>
          <button
            onClick={copyToClipboard}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-slate-700 hover:bg-slate-600 text-slate-200 rounded text-xs font-medium transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            {copied ? 'Copied!' : 'Copy Code'}
          </button>
        </div>
        <div className="p-6 overflow-auto text-slate-300 text-sm font-mono whitespace-pre text-left leading-relaxed">
          {generateFixtureCode()}
        </div>
      </div>
    </div>
  );
}
